# 1. Create a 3x3x3 array with random values 

In [1]:
import numpy as np

x = np.random.random((3,3,3))
print(x)

[[[0.88169665 0.77563875 0.10656327]
  [0.31337864 0.60439027 0.05516137]
  [0.36431937 0.20291113 0.17431091]]

 [[0.97251483 0.32337693 0.77946867]
  [0.53111645 0.53616503 0.38831987]
  [0.11114594 0.56509157 0.90756448]]

 [[0.08965156 0.13536749 0.1175949 ]
  [0.18990069 0.39516294 0.56076678]
  [0.4000758  0.95146981 0.54209255]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [2]:
x = np.diag(1+np.arange(4), k = -1)
print(x)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [5]:
y = np.zeros((8,8,))
y[::2, 1::2] = 1
y[1::2, ::2]= 1
print(y)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


# 4. Normalize a 5x5 random matrix

In [7]:
y = np.random.random((5,5))
ymin = y.min()
ymax = y.max()
y = (y - ymin) / (ymax - ymin)
print(y)

[[0.20439637 0.59812903 0.42764074 0.33365769 0.68291922]
 [1.         0.8801793  0.         0.16686768 0.97492667]
 [0.76459647 0.85267302 0.98205262 0.24120008 0.30976224]
 [0.70792177 0.41477354 0.36209778 0.05786428 0.9092333 ]
 [0.42397132 0.55526596 0.92880385 0.5292912  0.73743539]]


# 5.  How to find common values between two arrays?

In [11]:
x = [1,2,4,56,66,0]
y = [43,22,3,7,2, 1,0]

print('Array X ',x)
print("Array Y ",y)
print('')

print("Common values between two arrays:")
print(np.intersect1d(x, y))

Array X  [1, 2, 4, 56, 66, 0]
Array Y  [43, 22, 3, 7, 2, 1, 0]

Common values between two arrays:
[0 1 2]


# 6.How to get the dates of yesterday, today and tomorrow?

In [15]:
# Yesterday Date
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print('Yesterday', yesterday)

# Today's Date
today = np.datetime64('today', 'D')
print("Today's Date",today)

# Tomorrow's Date
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print('Tomorrow Date', tomorrow)

Yesterday 2020-07-26
Today's Date 2020-07-27
Tomorrow Date 2020-07-28


# 7. Consider two random array A and B, check if they are equal

In [16]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal)

False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [23]:
x = np.random.random(10)
x[x.argmax()] = 0
print(x)

[0.86086084 0.01279031 0.         0.85523699 0.38227162 0.0449438
 0.2955043  0.56540461 0.24859554 0.85266484]


# 9. How to print all the values of an array?

In [24]:
x = np.random.random(20)
print(x)

[0.89261098 0.62724217 0.14958515 0.274178   0.90436662 0.21610653
 0.70775438 0.86085704 0.3743503  0.89345049 0.83868342 0.1508974
 0.5250211  0.65790774 0.78301412 0.4268326  0.98952705 0.44454544
 0.31508999 0.83270569]


# 10.Subtract the mean of each row of a matrix

In [27]:
x = np.random.rand(5, 10)
y = x - x.mean(axis=1,keepdims=True)
print(x)
print(y)

[[0.71021888 0.33078098 0.95338254 0.50173368 0.37595965 0.57864371
  0.35068204 0.26140368 0.86254683 0.48195482]
 [0.06985797 0.18498939 0.57095543 0.28884027 0.46778843 0.98889838
  0.80230367 0.77759657 0.89626215 0.97530005]
 [0.56865075 0.71091175 0.5334407  0.64864656 0.1107468  0.8364971
  0.90312236 0.12557397 0.97929479 0.14578166]
 [0.8755843  0.13921757 0.90707172 0.55706979 0.46638039 0.49828421
  0.25892679 0.84036081 0.6179556  0.79433801]
 [0.27483111 0.29418324 0.45616119 0.17263402 0.98118149 0.29941848
  0.11795068 0.4458429  0.88584965 0.50805904]]
[[ 0.1694882  -0.2099497   0.41265186 -0.038997   -0.16477103  0.03791303
  -0.19004864 -0.279327    0.32181615 -0.05877586]
 [-0.53242126 -0.41728984 -0.0313238  -0.31343896 -0.1344908   0.38661915
   0.20002444  0.17531734  0.29398292  0.37302082]
 [ 0.01238411  0.1546451  -0.02282594  0.09237991 -0.44551984  0.28023046
   0.34685571 -0.43069267  0.42302815 -0.41048498]
 [ 0.28006538 -0.45630135  0.3115528  -0.03844913 

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [28]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[3. 3. 4. 2. 4. 3. 3. 2. 3. 3.]


# 12.How to get the diagonal of a dot product?

In [30]:
A = np.random.randint(0,10,(3,3))
B= np.random.randint(0,10,(3,3))
print('A ',A)
print('B ', B)
print(np.sum(A * B.T, axis=1))

A  [[2 8 8]
 [3 3 6]
 [6 4 5]]
B  [[9 9 6]
 [1 7 8]
 [4 0 1]]
[58 48 73]


# 13.How to find the most frequent value in an array?

In [32]:
x = np.random.randint(0,10,50)

print(x)

print('rank:', np.bincount(x).argmax())

[5 5 1 7 4 0 4 4 1 6 9 4 7 8 3 4 9 8 7 3 7 6 6 8 5 3 5 9 3 8 5 2 6 7 9 5 2
 8 6 5 8 3 7 6 3 5 6 5 4 7]
rank: 5


# 14.How to get the n largest values of an array

In [33]:
x = np.arange(10000)
np.random.shuffle(x)
n = 5
print (x[np.argpartition(-x,n)[:n]])

[9997 9999 9998 9996 9995]


# 15.How to create a record array from a regular array?

In [34]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')