In [17]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import BernoulliNB
from sklearn.metrics import accuracy_score,confusion_matrix, plot_confusion_matrix
import numpy as np
%matplotlib

Using matplotlib backend: Qt5Agg


In [2]:
titanic = pd.read_csv('https://raw.githubusercontent.com/LetsUpgrade/AI-ML-July-2020/master/Day-24/Dataset/train.csv')

In [3]:
titanic.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [4]:
titanic.shape

(889, 12)

In [5]:
titanic.describe

<bound method NDFrame.describe of      PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
884          887         0       2   
885          888         1       1   
886          889         0       3   
887          890         1       1   
888          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                 

In [6]:
titanic.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

Label Encoder

In [7]:
le = LabelEncoder()
titanic['Sex'] = le.fit_transform(titanic['Sex'])
titanic['Embarked'] = le.fit_transform(titanic['Embarked'])

In [8]:
titanic.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    1  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    0  38.0      1      0   
2                             Heikkinen, Miss. Laina    0  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    0  35.0      1      0   
4                           Allen, Mr. William Henry    1  35.0      0      0   

             Ticket     Fare Cabin  Embarked  
0         A/5 21171   7.2500   NaN         2  
1          PC 17599  71.2833   C85         0  
2  STON/O2. 3101282   7.9250   NaN         2  
3            113803  53.1000  C123         2  
4            373450   8.0500   NaN         2

In [9]:
titanic.dropna(inplace=True)
titanic.drop_duplicates(inplace=True)

Bernoulli Naive Bayes

In [10]:
model = BernoulliNB()

In [13]:
titanic.drop(columns = ['Cabin', 'PassengerId', 'Name', 'Ticket'], inplace=True)

Spliting data to Training and Testing

In [14]:
def naivemodel(X, y, rstate):
    X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=0)
    y_pred = model.fit(X_train, y_train).predict(X_test)
    acc = accuracy_score(y_test, y_pred, normalize=True)
    con = confusion_matrix(y_test, y_pred)
    return [acc, con]

In [20]:
rstate=-1
models =[]
for i, column in enumerate(titanic.columns[1:]):
    if column == 'Age' or column == 'Fare':
        continue
    y = titanic.iloc[:, i+1:i+2]
    X = titanic.drop(columns = y.columns)
    rstate += 1
    models.append([naivemodel(X, y, rstate), y.columns[0]])
    

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), 

In [22]:
for mlmodel in models:
    print(f'{mlmodel[1]} vs All\n')
    print(f'Accuracy: {mlmodel[0][0]}')
    print(f'Confusion Matrix: \n {mlmodel[0][1]}\n')
    print(f"Out of total 267 records only {np.trace(mlmodel[0][1])} are successfully classified, giving a model accuracy of {int(mlmodel[0][0]*100)}%.")
    print('\n-----------------------\n')

Pclass vs All

Accuracy: 0.9024390243902439
Confusion Matrix: 
 [[37  0  0]
 [ 3  0  0]
 [ 1  0  0]]

Out of total 267 records only 37 are successfully classified, giving a model accuracy of 90%.

-----------------------

Sex vs All

Accuracy: 0.7560975609756098
Confusion Matrix: 
 [[17  6]
 [ 4 14]]

Out of total 267 records only 31 are successfully classified, giving a model accuracy of 75%.

-----------------------

SibSp vs All

Accuracy: 0.4878048780487805
Confusion Matrix: 
 [[17  3  0  0]
 [16  3  0  0]
 [ 1  0  0  0]
 [ 1  0  0  0]]

Out of total 267 records only 20 are successfully classified, giving a model accuracy of 48%.

-----------------------

Parch vs All

Accuracy: 0.6585365853658537
Confusion Matrix: 
 [[27  0  0]
 [ 9  0  0]
 [ 5  0  0]]

Out of total 267 records only 27 are successfully classified, giving a model accuracy of 65%.

-----------------------

Embarked vs All

Accuracy: 0.4634146341463415
Confusion Matrix: 
 [[ 3  0 14]
 [ 0  0  2]
 [ 6  0 16]]

Out of 